# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "frankielp"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "4D Generative":
        filters: ["Image-to-4D", "Text-to-4D", "4D Generation"]
    "3D Generative":
        filters: ["Image-to-4D", "Text-to-3D", "3D Generation"]
    "3D Gaussian Splatting":
        filters: ["3D Gaussian Splatting", "GS3D"]
    "NeRF":
        filters: ["NeRF"]
    "Text-to-Video":
        filters: ["Text2Video","Text-to-Video"]
    "3D Vision":
        filters: ["3D", "Mesh"]
